name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: "openjdk@1.17.0"
          - os: ubuntu-latest
            java: "graalvm@21.1.0"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup
      uses: olafurpg/setup-scala@v11
      with:
        java-version: "${{ matrix.java }}"
    - name: Build and test
      run: sbt -v -Dfile.encoding=UTF8 +test
      shell: bash
